project/mysite/myapp/urls.py
from django.urls import path
from .views import upload_file
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('upload_csv/', upload_file, name='upload_csv'),
    path('download_excel/', views.download_excel, name='download_excel'),
    path('register/', views.register,name='register'),
    path('login/',views.user_login,name='login'), 
    path('home/',auth_view.LogoutView.as_view(template_name="myapp/home.html"),name='logout'), 
    path('upload/',auth_view.LogoutView.as_view(template_name="myapp/upload.html"),name='upload'), 
]

project/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    
    
]

project/mysite/myapp/models.py
from django.db import models
from django.conf import settings

class CSVData(models.Model):
    Index = models.IntegerField(default=0)
    M2_Declaration_Number = models.CharField(max_length=255)
    CIF_Value = models.FloatField()
    Stat_Quantity = models.FloatField()
    COMMODITY_DESC = models.CharField(max_length=255)
    GOODS_DESCRIPTION = models.CharField(max_length=255)
    unit_price = models.FloatField()
    Test = models.CharField(max_length=255)
    Test2 = models.CharField(max_length=255)

    def __str__(self):
        return f"Value :- {self.Index}"
    
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    

project/mysite/myapp/forms.py
from django import forms
from django.contrib.auth.models import User


class CSVUploadForm(forms.Form):
    csv_file = forms.FileField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistartionForm(forms.ModelForm):
     
     password = forms.CharField(label='password',widget=forms.PasswordInput)   
     password2 = forms.CharField(label='Confirm password',widget=forms.PasswordInput)   
     class Meta:
          model = User
          fields = {'username','email','first_name'}

     def check_password(self):
          if self.cleaned_data['password'] != self.clenned_data['password2']:
             raise forms.ValidationError('passwords do not match')
          return self.cleaned_data['password2']

project/mysite/myapp/views.py
import difflib
import csv
from io import BytesIO
from django.shortcuts import render
import pandas as pd
from .forms import CSVUploadForm,LoginForm,UserRegistartionForm
from django.db import connection
from .models import CSVData,Profile
from django.http import HttpResponse,JsonResponse
from django.contrib.auth import authenticate,login



def user_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(request, username=data['username'],password=data['password'])
            if user is not None:
                login(request,user)
                
                return render(request,'myapp/upload.html')
                
            else:
                return HttpResponse("Invalid login")

    else:
       form = LoginForm()
    return render(request,'myapp/login.html',{'form':form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistartionForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            return render(request,'myapp/home.html')
    else:
        user_form = UserRegistartionForm()
    return render(request,'myapp/register.html',{'user_form': user_form})


# Create your views here.
def upload_file(request):
    if request.method == 'POST':
        form = CSVUploadForm(request.POST,request.FILES)
        
        if form.is_valid():
            # Check if the uploaded file is a CSV
            file_name = request.FILES['csv_file'].name
            if not file_name.endswith('.csv'):
                return JsonResponse({'error': 'Invalid file format. Please upload a CSV file.'})

            #read the contents of the file using pandas
            df = pd.read_csv(request.FILES['csv_file'])
            #Find unit price using formula
            df['unit_price'] = df['CIF Value']/df['Stat Quantity']
            df['unit_price'] = df['unit_price'].apply(lambda x: round(x, 2))
            #grouped using groupby function
            grouped = df.groupby('M2_Declaration_Number')
            print(grouped)
            #find a average of unitprice
            group_averages = grouped['unit_price'].mean()
            print(group_averages)
            def check_price(row):
                group_avg = group_averages[row['M2_Declaration_Number']]
                group_avg_p = (group_avg*10)/100
                group_avg_pl = group_avg - group_avg_p
                group_avg_o = group_avg + group_avg_p
                if row['unit_price'] < group_avg_pl:
                    return "Undervalue"
                elif row['unit_price'] > group_avg_o:
                    return "Overvalue"
                else :
                    return "Expected"   
            df['Test'] = df.apply(check_price, axis=1)
            # Assuming your dataset is stored in a pandas DataFrame called `df`

            
        def check_price2(row):
                #split GOODS_DESCRIPTION using .split function
                expected_words = row['GOODS_DESCRIPTION'].split()
                print(expected_words)  
                #convert COMMODITY_DESC into upper letter using upper function for avoid case sensitive 
                commodity_desc = row['COMMODITY_DESC'].upper()
                print(commodity_desc)
                #loop for compare each word with commodity_desc 
                for word in expected_words:
                    print(f"Is '{word}' in '{commodity_desc}'? {word in commodity_desc}")
                #use any function is any word is match
                commodity_contains_expected = any(word in commodity_desc for word in expected_words)
                print(commodity_contains_expected)
                
                if commodity_contains_expected == True:
                      
                    print("one or more expected word")
                    return "True"
                    
                else:
                    print(f"Item is an expected import/export.")
                    return "False"
                  
        df['Test2'] = df.apply(lambda row: check_price2(row), axis=1) 
        df = df.drop(['Unnamed: 0'], axis=1) 

         # Add default value for CIF_Value if not present in the CSV file
        if 'CIF Value' not in df.columns:
                df['CIF Value'] = 0
            
            # Create a list of CSVData instances from the DataFrame rows
            
        csv_data_list = []
        for _, row in df.iterrows():
            existing_records = CSVData.objects.filter(
                Index=row['index'],
                M2_Declaration_Number=row['M2_Declaration_Number'],
                COMMODITY_DESC=row['COMMODITY_DESC'],
                GOODS_DESCRIPTION=row['GOODS_DESCRIPTION'],
                Stat_Quantity=row['Stat Quantity'],
                CIF_Value=row['CIF Value'],
                unit_price=row['unit_price'],
                Test=row['Test'],
                Test2=row['Test2']
            )
            if not existing_records:
                csv_data_list.append(CSVData(
                    Index=row['index'],
                    M2_Declaration_Number=row['M2_Declaration_Number'],
                    COMMODITY_DESC=row['COMMODITY_DESC'],
                    GOODS_DESCRIPTION=row['GOODS_DESCRIPTION'],
                    Stat_Quantity=row['Stat Quantity'],
                    CIF_Value=row['CIF Value'],
                    unit_price=row['unit_price'],
                    Test=row['Test'],
                    Test2=row['Test2']
            ))
        # Bulk insert the CSVData instances to the database
        CSVData.objects.bulk_create(csv_data_list) 
        
       # csv_data_list = [CSVData(
                
        #       Index = row['index'],
         #       COMMODITY_DESC = row['COMMODITY_DESC'],
          #      GOODS_DESCRIPTION = row['GOODS_DESCRIPTION'],
           #     Stat_Quantity=row['Stat Quantity'],
            #   CIF_Value=row['CIF Value'],
             #   unit_price=row['unit_price'],
             #   Test=row['Test'],
              #  Test2=row['Test2']
         #   ) for _, row in df.iterrows()]
            
            # Bulk insert the CSVData instances to the database
        #CSVData.objects.bulk_create(csv_data_list)
        #csv_data_list.save()
        #pass the dataframe to a templates
        return render(request,'myapp/data.html',{'data':df.to_html()})       
        
    else:
        form = CSVUploadForm()
    return render(request,'myapp/upload_csv.html',{'form':form})


def download_excel(request):
    
    # Get the data from the database
    data = CSVData.objects.all().values()
    df = pd.DataFrame(data)  # retrieve data from database or create DataFrame
    output = BytesIO()
    writer = pd.ExcelWriter(output, engine='xlsxwriter')
    df.to_excel(writer, sheet_name='Sheet1')
    writer.save()
    filename = 'data.xlsx'
    response = HttpResponse(output.getvalue(), content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response

project/mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
  <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
 <!-- <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">-->
  
  
</head>
<body>
  
  <nav class="shadow-lg p-5 bg-white ">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
      <a href="{% url 'logout' %}" class="flex">
        
        <span class="self-center text-xl font-bold">🏡Home</span>
        
      </a>
    </div>
    
  </nav>
 
 
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

project/mysite/myapp/templates/myapp/base2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
  <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
 <!-- <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">-->
  
  
</head>
<body>
  <header>
        
  </header>
  <nav class="shadow-lg p-5 bg-white flex  ">
    <div class="container flex flex-wrap justify-between items-center ">
      <a href="{% url 'logout' %}" >
        
        <span class="self-center text-xl font-bold">🏡Home</span>
        
      </a>
    </div>
    
    
    <div class="flex items-center justify-end">
        {% if request.user.is_authenticated %}
        <a class="py-4 px-2 text-blue-500 font-semibold" href="{% url 'logout' %}">Signout</a>
        {% else %}
        <button  class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded mr-4">
            <a  href="{% url 'login' %}">Signin</a>
        </button>
        {% endif %}
        <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'register' %}">
          Register
        </a>
      </div>


            
 </nav>
 
   
   
  
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

project/mysite/myapp/templates/myapp/data.html
<style>
    h1 {
    display: block;
    font-size: 2em;
    padding-top: 2px;
    font-weight: bold;
    color: #5c59ff;
   
    }
    table {
    
    color: rgb(0, 0, 0);
    text-align: center;
    margin-left: 25px;
    }
    th {
    display: table-cell;
    vertical-align: inherit;
    font-weight: bold;
    text-align: -internal-center;
    border-radius: 5px;
    padding: 4px;
    margin: 3px;
    }
tr {
    display: table-row;
    vertical-align: inherit;
    border-color: inherit;
}

td.element.style {
    width: 140.450;
}
.dataframe td:nth-child(10) {
  width: 300px;
  
}
a:hover {
  background-color: rgb(0, 132, 255)
}
</style>
{% block content %}
<div style="display: flex; ">
<h1 style="margin-left: 20px;">📒.....Data</h1>
<div style="margin-left: auto;">
<button type="submit" id="but" style=" background-color: rgb(117, 87, 253);  border-radius: 10px; border: white; height: 40px; margin-right: 40px; margin-top: 30px;">
    <a href="{% url 'download_excel' %}" class="btn btn-primary" style="color: aliceblue; "><b>Download</b></a>
</button>
<button type="submit" id="but" style=" background-color: rgb(117, 87, 253);  border-radius: 10px; border: white; height: 40px; margin-right: 40px; margin-top: 30px;">
     <a href="{% url 'upload_csv' %}" class="btn btn-primary" style="color: aliceblue;  "><b>Goback</b></a>
</button>
</div>
</div>
<hr style="border-bottom: solid rgb(126, 126, 126); margin-bottom: 20px;">


{{ data|safe }}


{% endblock %}

project/mysite/myapp/templates/myapp/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
  <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
 <!-- <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">-->
  
  
</head>
<body>
  <header>
        
  </header>
  <nav class="shadow-lg p-5 bg-white flex  ">
    <div class="container flex flex-wrap justify-between items-center ">
      <a href="#" >
        
        <span class="self-center text-xl font-bold">🏡Home</span>
        
      </a>
    </div>
    
    
    <div class="flex items-center justify-end">
        {% if request.user.is_authenticated %}
        <a class="py-4 px-2 text-blue-500 font-semibold" href="{% url 'logout' %}">Signout</a>
        {% else %}
        <button  class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded mr-4">
            <a  href="{% url 'login' %}">Signin</a>
        </button>
        {% endif %}
        <a class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" href="{% url 'register' %}">
          Register
        </a>
      </div>


            
 </nav>
 
   
   
  
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Import/Export Project</title>
  <!-- Add your CSS and JavaScript files here -->
  <link rel="stylesheet" href="styles.css">
  <script src="main.js"></script>
</head>

<body>
  <!-- Header section -->
  <header class="bg-blue-500 text-white text-center py-8">
    <h1 class="text-5xl font-bold">Welcome to Our Import/Export Project</h1>
    <p class="text-lg mt-4">Efficient and Reliable Global Trading Solutions</p>
  </header>

  <!-- Hero section -->
  <section class="bg-gray-200 py-16">
    <div class="container mx-auto">
      <div class="flex flex-wrap items-center justify-center">
        <div class="w-full md:w-1/2 px-8">
          <h2 class="text-3xl font-bold mb-4">Export Your Products Worldwide</h2>
          <p class="text-lg">We provide comprehensive export services to help you expand your business internationally. Our team of experts will handle all the logistics and documentation to ensure a smooth and hassle-free export process.</p>
        </div>
        <div class="w-full md:w-1/2 px-8">
            <div class="bg-cover bg-center h-screen" style="background-image: url('https://example.com/image.jpg');">

         </div>
      </div>
    </div>
  </section>

  <!-- Services section -->
  <section class="bg-white py-16">
    <div class="container mx-auto">
      <h2 class="text-3xl font-bold text-center mb-8">Our Services</h2>
      <div class="flex flex-wrap items-center justify-center">
        <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-8">
         <h3 class="text-xl font-bold mb-2">Shipping</h3>
          <p class="text-gray-600">We provide reliable shipping solutions for your products, ensuring timely and secure delivery to your customers worldwide.</p>
        </div>
        <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-8">
          <h3 class="text-xl font-bold mb-2">Customs Clearance</h3>
          <p class="text-gray-600">Our team of experts will handle all the customs clearance procedures, ensuring compliance with all relevant regulations and minimizing delays.</p>
        </div>
        <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-8">
          <h3 class="text-xl font-bold mb-2">Logistics</h3>
          <p class="text-gray-600">We offer end-to-end logistics solutions, including warehousing, transportation, and inventory management, to streamline your supply chain.</p>
        </div>

project/mysite/myapp/templates/myapp/login.html
{% block body %}
<h1 class="text-2xl m-10">&#128102; Login User</h1>
<div class="container ">
    <form method="POST" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="Username">Username</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10 ">{{ form.username }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="Username">Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10 ">{{ form.password }}</div>
        </div>
        
        
        <button class="text-white bg-green-500 px-5 py-2" type="submit">Login</button>
    </form>
</div>




<!DOCTYPE html>
<html>
<head>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f1f1f1;
		}
		.container {
			background-color: #fff;
			border-radius: 5px;
			box-shadow: 0 0 10px rgba(0,0,0,0.3);
			padding: 20px;
			margin: auto;
			max-width: 400px;
			margin-top: 100px;
		}
		input[type=text], input[type=password] {
			width: 100%;
			padding: 12px 20px;
			margin: 8px 0;
			display: inline-block;
			border: 1px solid #ccc;
			box-sizing: border-box;
			border-radius: 4px;
		}
		button {
			background-color: #0044ff;
			color: white;
			padding: 14px 20px;
			margin: 8px 0;
			border: none;
			cursor: pointer;
			width: 100%;
			border-radius: 4px;
		}
		button:hover {
			background-color: #45a049;
		}
	</style>
</head>

</html>

{% endblock %}

project/mysite/myapp/templates/myapp/register.html
{% block body %}
<h1 class="text-2xl m-10">&#128102; Register User</h1>
<div class="container ">
    <form method="POST" class="bg-white shadow-md m-10 w-2/5 rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Email</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10 ">{{ user_form.email }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Username</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10 ">{{ user_form.username }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Firstname</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10 ">{{ user_form.first_name }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10 ">{{ user_form.password }}</div>
        </div>
        <div class="mb-2">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="">Conform password</label>
            <div class="shadow text-gray-700 appearance-none border rounded py-2 px-3 mr-10 ">{{ user_form.password2 }}</div>
        </div>
        
        
        <button class="text-white bg-green-500 px-5 py-2" type="submit">Register</button>
    </form>
</div>


<!DOCTYPE html>
<html>
<head>
	<style>
		body {
			font-family: Arial, sans-serif;
			background-color: #f1f1f1;
		}
		.container {
			background-color: #fff;
			border-radius: 5px;
			box-shadow: 0 0 10px rgba(0,0,0,0.3);
			padding: 20px;
			margin: auto;
			max-width: 400px;
			margin-top: 40px;
		}
		input[type=text], input[type=password] ,input[type=email]{
			width: 100%;
			padding: 12px 20px;
			margin: 8px 0;
			display: inline-block;
			border: 1px solid #ccc;
			box-sizing: border-box;
			border-radius: 4px;
		}
		button {
			background-color: #0044ff;
			color: white;
			padding: 14px 20px;
			margin: 8px 0;
			border: none;
			cursor: pointer;
			width: 100%;
			border-radius: 4px;
		}
		button:hover {
			background-color: #45a049;
		}
	</style>
</head>

</html>

{% endblock %}

project/mysite/myapp/templates/myapp/upload.html
{% extends 'myapp/base2.html' %}
{% load static %}
{% block content %}
<div class="m-20">
    <b><h1 class="ml-20 my-2 mb-8 text-2xl text-green-500 font-bold">login Successfully</h1></b>
</div>

<div class="w-80 ml-40 ">
    <div class="container  mx-auto shadow-lg p-5  mt-20  border-4 bg-white">
    <h3 class="ml-10 my-2 mb-8 text-black-300 font-bold">Click Here For Go To Upload Page </h3>

      {% csrf_token %}
      
      <div class="mx-10 mt-8">
        <button type="submit" class="bg-blue-500 px-5 py-2 rounded-lg text-white font-bold">
            <a  href="{% url 'upload_csv' %}">Go TO Upload</a>
        </button>
      </div>
      
    
    </div>
  
  </div>

{% endblock %}

project/mysite/myapp/templates/myapp/upload_csv.html
{% extends 'myapp/base2.html' %}
{% load static %}
{% block content %}
<div class="flex ml-20">
 
<div class="w-100 ml-40 ">
  <div class="container  mx-auto shadow-lg p-5  mt-20  border-4 bg-white">
  <h1 class="ml-10 my-2 mb-8 text-2xl text-blue-500 font-bold">Upload Your file</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mx-10 mb-8 flex">
      <p>
        <input type="file" name="csv_file" required="" id="id_csv_file"class="bg-gray  rounded-lg text-black font-bold">
      </p>
    </div>
    
    <div class="mx-10 mt-8">
      <button type="submit" class="bg-blue-500 px-5 py-2 rounded-lg text-white font-bold">
        Uplode
      </button>
    </div>
    
  </form>
  </div>

</div>
<div class="m-20 pt-20" >
  <img src="{% static 'images/min.png' %}" alt="W3Schools.com"  width="130" height="140">
  
</div>
</div>
<script>
  window.addEventListener('load', function () {
    var csvFileInput = document.getElementById('id_csv_file');
    csvFileInput.focus();
  });

  const fileInput = document.getElementById('id_csv_file');
  fileInput.addEventListener('change', function () {
    const file = fileInput.files[0];
    if (!file || file.type !== 'text/csv') {
      alert('Please upload a CSV file.');
      fileInput.value = '';
    }
  });

  const uploadButton = document.getElementById('upload-button');
  const loadingAnimation = document.getElementById('loading-animation');

  uploadButton.addEventListener('click', () => {
    uploadButton.classList.add('hidden');
    loadingAnimation.classList.remove('hidden');
    setTimeout(() => {
      uploadButton.classList.remove('hidden');
      loadingAnimation.classList.add('hidden');
      // additional action after the animation ends
    }, 3000);
  });
</script>
{% endblock %}